# Generated by Django 4.2.3 on 2023-07-17 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0002_manga_language_manga_original_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manga',
            name='category',
        ),
        migrations.AddField(
            model_name='manga',
            name='category',
            field=models.ManyToManyField(to='manga.category'),
        ),
    ]
