# Generated by Django 4.2.3 on 2023-07-17 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0003_remove_manga_category_manga_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='total_volume',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='manga',
            name='volume',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
