# Generated by Django 4.2.3 on 2023-07-17 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0004_alter_manga_total_volume_alter_manga_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='total_volume',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='manga',
            name='volume',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
